Update WF_REL_TAC to use size_eq, MEM_SPLIT etc
HOL-Theorem-Prover/HOL pull request #975
Opened 2021-11-21 21:13 UTC by talsewell

Have WF_REL_TAC be able to clean up termination conjuncts as
well as the whole goal, and also make use of size_eqs, and
also have an extra (configurable) set of rewrites used only
if they remove a conjunct, which by default includes
MEM_SPLIT and list_size_append.

This allows a number of custom termination proofs to be reduced to
the relevant `WF_REL_TAC`. There's only a little breakage, for some
reason mostly in lisp-related examples. I've checked most CakeML
definitions are not affected.

2021-11-22 00:02 UTC, mn200 requested changes

2021-11-22 00:02 UTC, mn200 commented on src/boss/bossLib.sml
> +val _ = let
With `ThmSetData` in use, this addition should happen in `listScript.sml`

2021-11-22 00:02 UTC, mn200 commented on src/list/src/listScript.sml
> +val list_size_append = Q.store_thm("list_size_append",
Please use “modern” `Theorem` syntax for this.

2021-11-22 00:02 UTC, mn200 commented on src/num/termination/TotalDefn.sml
> +val termination_solve_simps = ref ([] : thm list);
I appreciate that the old code uses a reference; maybe fix that too :)

2021-11-22 11:54 UTC, talsewell commented
Thanks for looking Michael. Some if this isn't all that helpful. There's a reason I echo what's done in the surrounding code when I'm this far away from familiar contexts: it's just not clear to me which features are unavailable (we're before bossLib here), which are unwanted (e.g. Unicode), etc.

I'll update listScript right away. I now notice that if I'd scanned further in that file I'd have found plenty of other uses of the Theorem syntax. I guess that's available everywhere Q is (without [] attributes)?

I'll get around to reading about `ThmSetData` .. eventually.

2021-11-22 23:01 UTC, mn200 commented
Don't worry about the `ThmSetData` stuff; I'll do it myself.  `Theorem` syntax and attributes is available after `Q` (it maps to `Q.store_thm`). `Definition` is available after `num/termination`.

2021-11-22 23:02 UTC, merged

2021-11-23 09:54 UTC, talsewell commented
Thanks for looking into that Michael, and sorry about the grumpy comment.

I'd assumed that the use of `thm ref` was because this theorem set was only ever changed temporarily - I see now that I was wrong about that, and it's a huge improvement that some of the theory-hacking is gone.

It does look like there's a bit of boilerplate to set up the theorem set though. I was thinking of mentioning that in Isabelle there's a thing called named_theorems, which is just a wrapper around the more generic theory data mechanism. It simplifies things in the most common case, in which the dynamic data is just a flat list of theorems. I wonder if something like that might help here?

2021-11-24 00:17 UTC, mn200 commented
I made heavy weather of it because I wanted to additionally support removing theorems by name, and then I decided that the  underlying data structure should be a map from names to theorems.  But I agree that this sort of thing is likely to be a common case; it'd be worth providing such instances "for free" in `ThmSetData`.  Also an a-list form with names I suppose so that situations where the order is important I suppose.  Thanks for the suggestion.